name:  722Assignment_Carol
channels:
  - conda-forge
  - defaults
dependencies:
  - python= 3.11.3
  - cartopy>=0.21
  - geopandas
  - matplotlib_scalebar
  - os
  - notebook
  - pandas
  - pyepsg
  - openpyxl
